<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <title>{{$contest["name"]}}</title>
    <meta name="author" content="{{config('app.name')}}">
    <meta name="keywords" content="problemset,{{$contest["shortName"]}}">
</head>

@include("pdf.contest.css")
<style>
    @font-face {
        font-family: "DejaVu Sans";
        font-style: normal;
        font-weight: normal;
        src: url("{{asset('/static/fonts/dejaVu/DejaVuSans.ttf')}}") format("truetype");
    }

    @font-face {
        font-family: "DejaVu Sans";
        font-style: normal;
        font-weight: bold;
        src: url("{{asset('/static/fonts/dejaVu/DejaVuSans-Bold.ttf')}}") format("truetype");
    }

    @font-face {
        font-family: "DejaVu Sans";
        font-style: italic, oblique;
        font-weight: normal;
        src: url("{{asset('/static/fonts/dejaVu/DejaVuSans-Oblique.ttf')}}") format("truetype");
    }

    @font-face {
        font-family: "DejaVu Sans";
        font-style: italic, oblique;
        font-weight: bold;
        src: url("{{asset('/static/fonts/dejaVu/DejaVuSans-BoldOblique.ttf')}}") format("truetype");
    }

    @font-face {
        font-family: "DejaVu Serif";
        font-style: normal;
        font-weight: normal;
        src: url("{{asset('/static/fonts/dejaVu/DejaVuSerif.ttf')}}") format("truetype");
    }

    @font-face {
        font-family: "DejaVu Serif";
        font-style: normal;
        font-weight: bold;
        src: url("{{asset('/static/fonts/dejaVu/DejaVuSerif-Bold.ttf')}}") format("truetype");
    }

    @font-face {
        font-family: "DejaVu Serif";
        font-style: italic, oblique;
        font-weight: normal;
        src: url("{{asset('/static/fonts/dejaVu/DejaVuSerif-Italic.ttf')}}") format("truetype");
    }

    @font-face {
        font-family: "DejaVu Serif";
        font-style: italic, oblique;
        font-weight: bold;
        src: url("{{asset('/static/fonts/dejaVu/DejaVuSerif-BoldItalic.ttf')}}") format("truetype");
    }

    @font-face {
        font-family: "DejaVu Mono";
        font-style: normal;
        font-weight: normal;
        src: url("{{asset('/static/fonts/dejaVu/DejaVuSansMono.ttf')}}") format("truetype");
    }

    @font-face {
        font-family: "DejaVu Mono";
        font-style: normal;
        font-weight: bold;
        src: url("{{asset('/static/fonts/dejaVu/DejaVuSansMono-Bold.ttf')}}") format("truetype");
    }

    @font-face {
        font-family: "DejaVu Mono";
        font-style: italic, oblique;
        font-weight: normal;
        src: url("{{asset('/static/fonts/dejaVu/DejaVuSansMono-Oblique.ttf')}}") format("truetype");
    }

    @font-face {
        font-family: "DejaVu Mono";
        font-style: italic, oblique;
        font-weight: bold;
        src: url("{{asset('/static/fonts/dejaVu/DejaVuSansMono-BoldOblique.ttf')}}") format("truetype");
    }

    @font-face {
        font-family: 'simsun';
        font-style: normal;
        font-weight: normal;
        src: url("{{asset('/static/fonts/simsun/simsun.ttf')}}") format('truetype');
    }

    /* .pagenum:before {
        content: counter(page);
    } */

    /* .header {
        position: fixed;
        top: -30px;
        left: 0px;
        right: 0px;
        border-bottom: 1px solid #000;
    }

    .footer {
        position: fixed;
        bottom: 0px;
        left: 0px;
        right: 0px;
        font-style: italic;
    }

    .footer>span:last-of-type {
        position: absolute;
        right: 0;
    } */

    div.page-breaker {
        clear: both;
        display: block;
        border: 1px solid transparent;
        page-break-after: always;
    }

    html {
        font-size: 20px;
        line-height: 1.5;
        font-family: "DejaVu Serif", "simsun", serif;
    }

    body {
        font-size: 16px;
    }

    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
        font-family: "DejaVu Sans", "simsun", sans-serif;
    }

    code {
        font-family: "DejaVu Mono", "simsun", monospace;
    }

    div.sample-container,
    img.sample-container {
        page-break-inside: avoid;
    }

    .rendered-tex {
        padding: 0 0.25rem;
        /* vertical-align: middle; */
        /* margin-bottom: -2px; */
    }

    code {
        color: #000;
        border-radius: 3px;
        padding: .2em 0;
        font-style: normal;
        font-weight: 300;
    }
</style>

{{-- <div class="header">Generated by NOJ - https://github.com/ZsgsDesign/NOJ</div>
<div class="footer"><span>{{$contest["shortName"]}}</span> <span>Page <span class="pagenum"></span></span></div> --}}

{{-- Cover Page --}}
@if($conf['cover']) @include('pdf.contest.cover',['contest'=>$contest,'problemset'=>$problemset]) @endif

{{-- Advice Page --}}
@if($conf['advice']) @include('pdf.contest.advice') @endif

{{-- ProblemSet --}}
@foreach ($problemset as $problem)

@include('pdf.contest.problem', ['problem'=>$problem])

@unless($loop->last)<div class="page-breaker"></div>@endunless

@endforeach

@include("pdf.contest.mathjax")
