<style>
    .pagenum:before {
        content: counter(page);
    }

    .header {
        position: fixed;
        top: -30px;
        left: 0px;
        right: 0px;
        border-bottom: 1px solid #000;
    }

    .footer {
        position: fixed;
        bottom: 0px;
        left: 0px;
        right: 0px;
        font-style: italic;
    }

    .footer>span:last-of-type {
        position: absolute;
        right: 0;
    }
</style>
<div class="header">Generated by NOJ - https://github.com/ZsgsDesign/NOJ</div>
<div class="footer"><span>{{$contest["shortName"]}}</span> <span>Page <span class="pagenum"></span></span></div>
